spring:
  application:
    name: SERVICE-HI
server:
  port: 9999
message: kkk
name: xxx
password: sss
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true